#!/bin/sh
# get info 
wm=$DESKTOP_SESSION
os=$(cat /etc/os-release | grep ^NAME | awk -F'"' '{print $2}')
kernel=$(uname -r)
shell=$(ps -o comm= -p "$PPID")

# color strip from info-mono's colorstrip
# https://github.com/info-mono/colorstrip
# logo that i stole and changed from info-mono's os-ansi
# https://github.com/info-mono/os-ansi

echo -e "

       \e[2;36m___\e[0m	\e[36m$(whoami)\e[0m@\e[36m$(cat /etc/hostname)\e[0m
      \e[2;36m(\e[0m.. \e[2;36m|\e[0m	\e[36mOS:\e[0m ${os}
      \e[2;36m(\e[0m\e[33m<>\e[0m \e[2;36m|\e[0m	\e[36mKernel:\e[0m ${kernel}
     \e[2;36m/\e[0m __  \e[2;36m\ \e[0m	\e[36mShell:\e[0m ${shell}
    \e[2;36m(\e[0m /  \ \e[2;36m |\e[0m	\e[36mWM:\e[0m ${wm}
  \e[33m_\e[2;36m/ \e[0m \__/ \e[33m_\e[0m\e[2;36m)\e[0m	\e[0;30m███\e[0;31m███\e[0;32m███\e[0;33m███\e[0;34m███\e[0;35m███\e[0;36m███\e[0;37m███\e[0m
  \e[33m\/\e[2;36m______\e[0m\e[33m\/\e[0m	\e[0;1;90m███\e[0;1;91m███\e[0;1;92m███\e[0;1;93m███\e[0;1;94m███\e[0;1;95m███\e[0;1;96m███\e[0;1;97m███\e[0m


"
